mass rename to avoid clashes with core tap
Forgot that base formula names need to be unique, otherwise `brew upgrade` picks up the core tap formula over this replacement, leading to:
```
$ brew upgrade
[...]
==> Upgrading sshfs 2.10_2 -> 3.7.1
Error: sshfs has been disabled because it requires FUSE!
```